version: '3.8'
services:
  postgres:
    image: postgres:13.3-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env

  seeder:
    image: 08c552ca5ffa4e6cba77a85d1af9e47cdf67b6c41d3afede2c9aecbe63b058f8
    container_name: seeder
    env_file:
      - .env

volumes:
  postgres:
