version: '3.8'
services:
  postgres:
    image: postgres:13.3-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .db.env

volumes:
  postgres:
